# Render the full five-arm NHANES results (completed local 3-learner analysis) as
# a compact LaTeX table for Web Appendix F. Transposed (arms as rows, E1-E4 as
# columns) so it fits the page. Numbers straight from local_preview_summary.csv.
# Output: Writing/Appendix/webF_arms.tex
d <- read.csv("Nhanes/results/local_preview_summary.csv", check.names = FALSE)
exs <- c("E1", "E2", "E3", "E4")
arms <- c("Non-Aware", "Partially-Aware", "Fully-Aware", "Fully-Aware-CV", "Fully-Aware-CF")
arm_lab <- c("Non-Aware", "Partially-Aware", "Fully-Aware",
             "Fully-Aware-CV", "\\textbf{Fully-Aware-CF}")
names(arm_lab) <- arms
cell <- function(ex, m) {
  r <- d[d$example == ex & d$method == m, ]
  if (nrow(r) == 0) return("")
  # round half away from zero (matches main-text Table 2, e.g. 0.0355 -> 0.036)
  num <- function(x) gsub("-", "$-$", sprintf("%.3f", x + sign(x) * 5e-7))
  sprintf("%s (%s, %s)", num(r$b), num(r$lcl), num(r$ucl))
}
out <- c("% Auto-generated by Nhanes/R/render_arms_tex.R -- do not edit by hand.",
         "% Source: Nhanes/results/local_preview_summary.csv (local 3-learner preview).",
         "\\begin{table}[H]\\centering\\small",
         "\\caption{Five-arm NHANES results (local three-learner Super Learner $\\{$GLM, MARS, LASSO$\\}$): the population ATE on the risk-difference scale (95\\% confidence interval) for each design-awareness level, for the four illustrations E1 (short sleep $\\to$ obesity), E2 (food insecurity $\\to$ depression), E3 (e-cigarette use $\\to$ hypertension), and E4 (gestational diabetes $\\to$ hypertension). The point estimate is broadly stable across arms; relative to the single-fit Fully-Aware estimator the certified cross-fitted Fully-Aware-CF arm gives an interval that is no wider---and the narrowest of the design-aware arms in E2 and E3---because out-of-fold targeting bounds the estimated propensity. Where the substantive conclusion shifts (E3), the shift occurs at the Non-Aware $\\to$ Partially-Aware (survey-weighting) step, not at cross-fitting. Fully-Aware is the single-fit estimator and Fully-Aware-CF (cross-fitted) is the certified primary.}",
         "\\label{tab:webF_arms}",
         "\\begin{tabular}{@{}l cccc@{}}",
         "\\toprule",
         "Estimator & E1 & E2 & E3 & E4 \\\\",
         "\\midrule")
for (m in arms) {
  out <- c(out, sprintf("%s & %s & %s & %s & %s \\\\",
                        arm_lab[[m]], cell("E1", m), cell("E2", m), cell("E3", m), cell("E4", m)))
}
out <- c(out, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(out, "Writing/Appendix/webF_arms.tex")
cat(paste(out, collapse = "\n"), "\n")
