# Render the R03 cross-fitting-vs-de-weighting 2x2 isolation as a compact LaTeX
# table for Web Appendix D. Arms as rows (SF-W, SF-U, CF-W, CF-U), grouped by
# rung (L4_aggressive demonstration, then L1_param placebo); columns are the
# usable replicate count, bias, coverage, and SE-to-SD ratio. Numbers straight
# from results/arc/R03_isolation_2x2_summary.csv (the aggregate.R output).
# Output: Writing/Appendix/webD_isolation.tex
# Run from the repo root: Rscript Nhanes/R/render_isolation_tex.R
d <- read.csv("results/arc/R03_isolation_2x2_summary.csv",
              stringsAsFactors = FALSE)

rungs    <- c("L4_aggressive", "L1_param")
rung_lab <- c(L4_aggressive = "L4 (aggressive)", L1_param = "L1 (param)")
arms     <- c("SF-W", "SF-U", "CF-W", "CF-U")
arm_lab  <- c("SF-W", "SF-U", "CF-W", "CF-U")
names(arm_lab) <- arms

f3  <- function(x) sprintf("%.3f", x)
sf3 <- function(x) gsub("-", "$-$", sprintf("%+.3f", x + sign(x) * 5e-7))  # signed bias
f2  <- function(x) sprintf("%.2f", x)
# usable n / diverged label: show only the diverged count when non-zero
ncell <- function(nr, nd) if (nd > 0) sprintf("%d (%d div.)", nr, nd) else sprintf("%d", nr)

out <- c(
  "% Auto-generated by Nhanes/R/render_isolation_tex.R -- do not edit by hand.",
  "% Source: results/arc/R03_isolation_2x2_summary.csv (R03 isolation 2x2).",
  "\\begin{table}[H]\\centering\\small",
  paste0("\\caption{Isolating cross-fitting from de-weighting: a $2\\times2$ design ",
         "crossing single-fit (SF) versus cross-fit (CF) with weighted (W) versus ",
         "unweighted (U) out-of-fold nuisances, at a harmonized $0.05$ propensity ",
         "floor for all arms (standard design, $1{,}000$ replicates). At the ",
         "aggressive rung (L4) single-fit under-covers whether or not the weights ",
         "are dropped, while both cross-fit arms recover to near nominal---so ",
         "cross-fitting, not de-weighting, drives the coverage rescue. At the ",
         "parametric placebo rung (L1) all arms are near nominal. `$n$' is the ",
         "number of usable (converged) replicates; the two weighted L1 arms each ",
         "dropped replicates whose pooled targeting diverged at the floor. ",
         "SE/SD is the mean estimated standard error divided by the empirical ",
         "standard deviation of the point estimates.}"),
  "\\label{tab:webD_iso}",
  "\\begin{tabular}{@{}ll r r r r@{}}",
  "\\toprule",
  "Rung & Arm & $n$ & Bias & Coverage & SE/SD \\\\",
  "\\midrule")

for (r in rungs) {
  first <- TRUE
  for (m in arms) {
    rr <- d[d$rung == r & d$method == m, ]
    if (nrow(rr) == 0) next
    rhead <- if (first) rung_lab[[r]] else ""
    cov <- f3(rr$coverage)
    if (r == "L4_aggressive") {
      # bold the decisive coverage cells at the demonstration rung
      cov <- sprintf("\\textbf{%s}", cov)
    }
    out <- c(out, sprintf("%s & %s & %s & %s & %s & %s \\\\",
                          rhead, arm_lab[[m]], ncell(rr$n_reps, rr$n_diverged),
                          sf3(rr$bias), cov, f2(rr$se_ratio)))
    first <- FALSE
  }
  if (r != rungs[length(rungs)]) out <- c(out, "\\addlinespace")
}

out <- c(out, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(out, "Writing/Appendix/webD_isolation.tex")
cat(paste(out, collapse = "\n"), "\n")
