# Render the informative-selection robustness table for Web Appendix F, from the
# R07 sweep. Rows are (rung x rho); columns give the certified de-weighted-OOF arm
# (Fully-Aware-CF-unwt) and the weighted-OOF comparator (Fully-Aware-CF-wt):
# absolute bias and coverage for each, plus the shared within-fold weight spread
# (w_cv) that confirms the selection is informative. Numbers straight from
# results/arc/R07_informative_summary.csv.
# Output: Writing/Appendix/webF_informative.tex
d <- read.csv("results/arc/R07_informative_summary.csv", stringsAsFactors = FALSE)

rhos     <- c(0, 0.3, 0.6, 0.9)
rungs    <- c("L2_smooth", "L3_adaptive")
rung_lab <- c(L2_smooth = "L2", L3_adaptive = "L3")
unwt <- "Fully-Aware-CF-unwt"
wt   <- "Fully-Aware-CF-wt"

f3 <- function(x) sprintf("%.3f", x + sign(x) * 5e-7)   # round half away from 0
f2 <- function(x) sprintf("%.2f", x + sign(x) * 5e-7)
get <- function(rho, rung, method, col) {
  r <- d[d$rho == rho & d$rung == rung & d$method == method, ]
  if (nrow(r) != 1) stop(sprintf("R07: expected 1 row for rho=%s %s %s", rho, rung, method))
  r[[col]]
}

out <- c(
  "% Auto-generated by Nhanes/R/render_informative_tex.R -- do not edit by hand.",
  "% Source: results/arc/R07_informative_summary.csv (R07 informative-selection sweep).",
  "\\begin{table}[H]\\centering\\small",
  paste0("\\caption{Robustness of the de-weighted out-of-fold (OOF) cross-fitted ",
         "estimator to informative selection. The selection-strength parameter ",
         "$\\rho$ correlates PSU inclusion with the outcome/exposure residual ",
         "(so $S$ is informative beyond $C$); the within-fold weight spread ",
         "$\\mathrm{CV}(w)$ rises with $\\rho$, confirming the design responds. ",
         "For each rung (L2 smooth, L3 adaptive) and each $\\rho$ we report the ",
         "absolute bias and $95\\%$ coverage of the certified arm with unweighted ",
         "OOF nuisances (Fully-Aware-CF-unwt) and of the comparator with weighted ",
         "OOF nuisances (Fully-Aware-CF-wt). Both arms hold near-nominal coverage ",
         "across the sweep and the de-weighted bias is flat-to-declining in ",
         "$\\rho$: the de-weighting choice (Web Appendix~B) is robust to ",
         "informative selection. Conclusions are anchored on L3.}"),
  "\\label{tab:webF_informative}",
  "\\begin{tabular}{@{}ll c cc cc@{}}",
  "\\toprule",
  " & & & \\multicolumn{2}{c}{Unwt OOF (certified)} & \\multicolumn{2}{c}{Wt OOF (comparator)} \\\\",
  "\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}",
  "Rung & $\\rho$ & $\\mathrm{CV}(w)$ & $|\\mathrm{bias}|$ & Coverage & $|\\mathrm{bias}|$ & Coverage \\\\",
  "\\midrule")

for (rg in rungs) {
  first <- TRUE
  for (rho in rhos) {
    rl <- if (first) rung_lab[[rg]] else ""
    out <- c(out, sprintf("%s & %s & %s & %s & %s & %s & %s \\\\",
                          rl, f2(rho),
                          f2(get(rho, rg, unwt, "w_cv")),
                          f3(abs(get(rho, rg, unwt, "bias"))), f3(get(rho, rg, unwt, "coverage")),
                          f3(abs(get(rho, rg, wt,   "bias"))), f3(get(rho, rg, wt,   "coverage"))))
    first <- FALSE
  }
  if (rg != rungs[length(rungs)]) out <- c(out, "\\addlinespace")
}

out <- c(out, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(out, "Writing/Appendix/webF_informative.tex")
cat(paste(out, collapse = "\n"), "\n")
