# =====================================================================
# Nhanes/R/render_sensitivity_tex.R
# R09 causal-validity sensitivity analyses -> Writing/Appendix/webF_sensitivity.tex
# Reads results/arc/R09_sensitivity_delta.csv (certified Fully-Aware-CF arm) and
# results/arc/R09_design_check.csv (SDMVSTRA cross-cycle non-overlap check).
# Each row = a modified-adjustment-set re-run of the certified primary, with the
# ATE/CI delta vs the same example's full-adjustment fit (single imputation, same
# library/seed). Conclusion-flip is whether the CI-excludes-0 verdict changed.
# =====================================================================
del <- read.csv("results/arc/R09_sensitivity_delta.csv", stringsAsFactors = FALSE)
dc  <- read.csv("results/arc/R09_design_check.csv", stringsAsFactors = FALSE)
cf  <- del[del$arm == "Fully-Aware-CF", ]

sgn  <- function(x) sub("^-", "$-$", sprintf("%.3f", round(x, 3)))
ci   <- function(b, l, u) sprintf("%s (%s, %s)", sgn(b), sgn(l), sgn(u))
verd <- function(s) ifelse(s, "excludes 0", "covers 0")

# fixed, human-readable adjustment-change labels (keyed by cell)
chg <- c(E1_noPHQ = "E1 sleep $\\to$ obesity, drop PHQ-9 depression",
         E2_noBMI = "E2 food insec.\\ $\\to$ depr., drop BMI (as mediator)",
         E4_noBMI = "E4 GDM $\\to$ HTN, drop BMI adiposity proxy")
ord <- c("E1_noPHQ", "E2_noBMI", "E4_noBMI")
cf  <- cf[match(ord, cf$cell), ]

L <- c(
  "% Auto-generated by Nhanes/R/render_sensitivity_tex.R -- do not edit by hand.",
  "% Source: results/arc/R09_sensitivity_delta.csv (Fully-Aware-CF) + R09_design_check.csv.",
  "\\begin{table}[H]\\centering\\small",
  paste0("\\caption{Causal-validity sensitivity analyses: the certified Fully-Aware-CF estimator (risk ",
         "difference, 95\\% CI) re-run on modified adjustment sets, against the same example's ",
         "full-adjustment fit (single imputation, same library and seed). No conclusion flips: ",
         "the food-insecurity$\\to$depression effect survives treating BMI as a mediator, the ",
         "short-sleep$\\to$obesity effect survives dropping PHQ-9, and the gestational-diabetes ",
         "estimate stays null without the post-exposure BMI proxy.}"),
  "\\label{tab:webF_sens}",
  "\\begin{tabular}{@{}l ll c@{}}",
  "\\toprule",
  "Adjustment-set change & Full-set RD (95\\% CI) & Modified RD (95\\% CI) & Conclusion \\\\",
  "\\midrule")
for (i in seq_len(nrow(cf))) {
  r <- cf[i, ]
  L <- c(L, sprintf("%s & %s & %s & %s $\\to$ %s \\\\",
                    chg[[r$cell]],
                    ci(r$b_main, r$lcl_main, r$ucl_main),
                    ci(r$b_sens, r$lcl_sens, r$ucl_sens),
                    verd(r$signif_main), verd(r$signif_sens)))
}
clean_all <- all(dc$overlap_clean %in% c(TRUE, "TRUE"))
L <- c(L,
  "\\bottomrule",
  "\\end{tabular}",
  sprintf(paste0("\\\\[2pt]\\footnotesize SDMVSTRA cross-cycle non-overlap check (all four examples): ",
                 "every sampling stratum lies in exactly one NHANES cycle (max cycles spanned $=%d$), ",
                 "so the pooled stratification and \\texttt{nest=TRUE} are valid."),
          max(dc$max_cycles_spanned)),
  "\\end{table}")

writeLines(L, "Writing/Appendix/webF_sensitivity.tex")
cat("wrote Writing/Appendix/webF_sensitivity.tex; design-check all clean:", clean_all, "\n")
cat(paste(L, collapse = "\n"), "\n")
