# Render the replication-variance check (delete-one-PSU survey jackknife vs.
# Taylor-series linearization, on the SAME influence function) as a LaTeX table
# fragment for Web Appendix F. Rows = design x rung x arm; columns compare the
# mean linearization SE, mean jackknife SE, their ratio, and the two coverages.
# Numbers straight from results/R11_resampling_eff_summary.csv (kind="jack").
# Output: outputs/tables/webF_jack.tex
d <- read.csv("results/R11_resampling_eff_summary.csv", stringsAsFactors = FALSE)
j <- d[d$kind == "jack", ]

scen     <- c("standard", "R1")                       # Design A (standard), Design B (R1)
scen_lab <- c(standard = "A (standard)", R1 = "B (informative)")
rungs    <- c("L1_param", "L3_adaptive")
rung_lab <- c(L1_param = "L1", L3_adaptive = "L3")
arms     <- c("Fully-Aware", "Fully-Aware-CF")
arm_lab  <- c("Fully-Aware" = "Fully-Aware",
              "Fully-Aware-CF" = "\\textbf{Fully-Aware-CF}")

f3  <- function(x) sprintf("%.3f", x)
r2  <- function(x) sprintf("%.2f", x)
get <- function(sc, ru, ar, col) {
  v <- j[[col]][j$scenario == sc & j$rung == ru & j$method == ar]
  if (length(v) == 1) v else NA_real_
}

out <- c(
  "% Auto-generated by simulation/enhancements/R11_resampling_eff/render_jack_tex.R -- do not edit by hand.",
  "% Source: results/R11_resampling_eff_summary.csv (kind=\"jack\" rows).",
  "\\begin{table}[H]\\centering\\small",
  paste0("\\caption{Replication-variance check: the design-based Taylor-series-",
         "linearization (TSL) standard error of Equation~(\\maineqvar) against a ",
         "delete-one-PSU survey jackknife computed on the \\emph{same} influence ",
         "function, for the single-fit Fully-Aware and the primary cross-fitted ",
         "Fully-Aware-CF arms, in both designs and at the parametric (L1) and ",
         "adaptive (L3) Super Learner rungs ($500$ replicates each). ",
         "`Ratio' is the mean per-replicate jackknife/linearization SE ratio; ",
         "values near $1$ corroborate Theorem~2. Coverages are the empirical ",
         "$95\\%$ Wald coverages built from the linearization SE and from the ",
         "jackknife SE, respectively.}"),
  "\\label{tab:webF_jack}",
  "\\begin{tabular}{@{}ll l ccc cc@{}}",
  "\\toprule",
  paste("Design & Rung & Estimator & TSL SE & Jackknife SE & Ratio &",
        "Cov.\\ (TSL) & Cov.\\ (jack) \\\\"),
  "\\midrule")

for (sc in scen) {
  first_sc <- TRUE
  for (ru in rungs) {
    for (ar in arms) {
      schead <- if (first_sc) scen_lab[[sc]] else ""
      ruhead <- if (ar == arms[1]) rung_lab[[ru]] else ""
      out <- c(out, sprintf("%s & %s & %s & %s & %s & %s & %s & %s \\\\",
                            schead, ruhead, arm_lab[[ar]],
                            f3(get(sc, ru, ar, "mean_se_taylor")),
                            f3(get(sc, ru, ar, "mean_se_jack")),
                            r2(get(sc, ru, ar, "jk_lin_ratio")),
                            f3(get(sc, ru, ar, "coverage_taylor")),
                            f3(get(sc, ru, ar, "coverage_jack"))))
      first_sc <- FALSE
    }
  }
  if (sc != scen[length(scen)]) out <- c(out, "\\addlinespace")
}

out <- c(out, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(out, "outputs/tables/webF_jack.tex")
cat(paste(out, collapse = "\n"), "\n")
