# Render the calibrated-(raked-)weights simulation check as a LaTeX table
# fragment for Web Appendix F. Design-A population; per replicate the SAME
# two-stage sample is analyzed twice: with the true design (HT) weights and
# with those weights raked to two known population margins (stratum counts x
# tertiles of the observed covariate L1) -- the practice-analogue of
# post-stratifying to demographic control totals, as in NHANES.
# Numbers straight from: results/J3_calib_summary.csv
# Output: outputs/tables/webF_calib.tex   (label tab:webF_calib)

a <- read.csv("results/J3_calib_summary.csv", stringsAsFactors = FALSE)

f3 <- function(x) sprintf("%.3f", x + sign(x) * 5e-7)

rungs    <- c("L1_param", "L2_smooth")
rung_lab <- c(L1_param = "L1", L2_smooth = "L2")
arms_for <- function(rung) if (rung == "L2_smooth")
  c("Fully-Aware", "Fully-Aware-CV", "Fully-Aware-CF") else c("Fully-Aware", "Fully-Aware-CF")
arm_lab  <- c("Fully-Aware"    = "Fully-Aware",
              "Fully-Aware-CV" = "Fully-Aware-CV",
              "Fully-Aware-CF" = "\\textbf{Fully-Aware-CF}")

G <- function(rung, arm, scheme, col) {
  v <- a[[col]][a$rung == rung & a$method == arm & a$weight_scheme == scheme]
  if (length(v) == 1) v else stop(sprintf("J3: no row for %s/%s/%s", rung, arm, scheme))
}

rows <- character(0)
for (rg in rungs) for (arm in arms_for(rg)) {
  rows <- c(rows, paste0(
    rung_lab[[rg]], " & ", arm_lab[[arm]],
    " & ", f3(G(rg, arm, "design", "bias")), " & ", f3(G(rg, arm, "design", "se_ratio")),
    " & ", f3(G(rg, arm, "design", "coverage")),
    " & ", f3(G(rg, arm, "raked",  "bias")), " & ", f3(G(rg, arm, "raked",  "se_ratio")),
    " & ", f3(G(rg, arm, "raked",  "coverage")), " \\\\"))
}

out <- c(
  "% Auto-generated by simulation/renderers/render_calib_tex.R -- do not edit by hand.",
  "% Source: results/J3_calib_summary.csv.",
  "\\begin{table}[H]\\centering\\small",
  paste0("\\caption{Calibrated (raked) versus design weights: simulation check ",
         "(Design~A, $1000$ replicates per cell). Each replicate's two-stage ",
         "sample is analyzed twice --- with the true inverse-inclusion (design) ",
         "weights and with those weights raked to two \\emph{known} population ",
         "margins (stratum counts $\\times$ tertiles of the observed covariate ",
         "$L_1$), the practice-analogue of post-stratification to demographic ",
         "control totals. Columns give bias, the mean design SE over the ",
         "empirical SD (SE/SD; $1$ is calibrated), and $95\\%$ Wald coverage, ",
         "under each weight set. The primary cross-fitted estimator's coverage ",
         "is unchanged by raking at both rungs, supporting the treatment of ",
         "calibrated weights as design weights in the NHANES application ",
         "(Remark on calibrated weights, Web Appendix~A). The Non-Aware and ",
         "Partially-Aware arms (not shown) are unaffected by construction; the ",
         "residual L1 bias is the Kang--Schafer misspecification of Web ",
         "Appendix~D, common to both weight sets.}"),
  "\\label{tab:webF_calib}",
  "\\begin{tabular}{@{}ll ccc ccc@{}}",
  "\\toprule",
  " & & \\multicolumn{3}{c}{Design weights} & \\multicolumn{3}{c}{Raked weights} \\\\",
  "\\cmidrule(lr){3-5}\\cmidrule(lr){6-8}",
  "Rung & Estimator & Bias & SE/SD & Coverage & Bias & SE/SD & Coverage \\\\",
  "\\midrule",
  rows,
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{table}")

writeLines(out, "outputs/tables/webF_calib.tex")
cat("wrote outputs/tables/webF_calib.tex\n")
