# Render the finite-population-correction (FPC) / first-stage-fraction robustness
# check as a two-panel LaTeX table fragment for Web Appendix F.
#   Panel A: primary design (R1) at rungs L1, L2, for the single-fit Fully-Aware
#            and cross-fitted Fully-Aware-CF arms, WITH vs WITHOUT the FPC; columns
#            give the design SE-to-SD ratio and the 95% Wald coverage. Shows the
#            no-FPC variance is calibrated (ratio ~ 1) and the FPC under-covers.
#   Panel B: primary Fully-Aware-CF at L1, sweeping the first-stage fraction
#            f = m/M_pop via J in {8,16,32,64}; columns give J, f, SE/SD ratio,
#            coverage. Shows insensitivity to f over 0.03-0.25.
# Numbers straight from:
#   results/R10_fpc_partA_summary.csv       (Panel A)
#   results/R10_fpc_fraction_sweep.csv      (Panel B)
# Output: outputs/tables/webF_fpc.tex   (label tab:webF_fpc)

a <- read.csv("results/R10_fpc_partA_summary.csv",   stringsAsFactors = FALSE)
b <- read.csv("results/R10_fpc_fraction_sweep.csv", stringsAsFactors = FALSE)

f3 <- function(x) sprintf("%.3f", x + sign(x) * 5e-7)   # round half away from 0
r3 <- function(x) sprintf("%.3f", x + sign(x) * 5e-7)   # SE/SD at 3 dp

rungs    <- c("L1_param", "L2_smooth")
rung_lab <- c(L1_param = "L1", L2_smooth = "L2")
arms     <- c("Fully-Aware", "Fully-Aware-CF")
arm_lab  <- c("Fully-Aware" = "Fully-Aware",
              "Fully-Aware-CF" = "\\textbf{Fully-Aware-CF}")

getA <- function(rung, arm, fpc, col) {
  v <- a[[col]][a$rung == rung & a$method == arm & a$fpc == fpc]
  if (length(v) == 1) v else stop(sprintf("R10 Panel A: no row for %s/%s/fpc=%s", rung, arm, fpc))
}
getB <- function(J, col) {
  v <- b[[col]][b$J == J]
  if (length(v) == 1) v else stop(sprintf("R10 Panel B: no row for J=%d", J))
}

out <- c(
  "% Auto-generated by codes/render_fpc_tex.R -- do not edit by hand.",
  "% Sources: results/R10_fpc_partA_summary.csv (Panel A);",
  "%          results/R10_fpc_fraction_sweep.csv (Panel B).",
  "\\begin{table}[H]\\centering\\small",
  paste0("\\caption{Finite-population-correction (FPC) and first-stage-fraction ",
         "robustness of the primary design-based variance (Design~B, the ",
         "NHANES-like two-PSU-per-stratum geometry; $1000$ replicates each). ",
         "`SE/SD' is the mean design standard error divided by the empirical ",
         "sampling standard deviation (calibration; $1$ is ideal); `Coverage' is ",
         "the empirical $95\\%$ Wald coverage. \\emph{Panel~A}: single-fit ",
         "Fully-Aware and primary Fully-Aware-CF at the parametric (L1) and ",
         "smooth (L2) rungs, computed without and with an FPC on the design ",
         "variance. Without the FPC the SE is calibrated ($\\mathrm{SE/SD}\\approx ",
         "1$); applying the FPC shrinks it ($\\approx 0.86$) and makes the interval ",
         "anti-conservative. \\emph{Panel~B}: primary Fully-Aware-CF at L1, ",
         "sweeping the first-stage fraction $f=m/M_{\\mathrm{pop}}$ via the number ",
         "of strata $J$; the SE stays calibrated and coverage is flat in $f$. The ",
         "slightly sub-nominal L1 coverages reflect the Kang--Schafer ",
         "misspecification bias of Web Appendix~D, not a variance defect.}"),
  "\\label{tab:webF_fpc}",
  "\\begin{tabular}{@{}ll cc@{}}",
  "\\toprule",
  "\\multicolumn{4}{@{}l}{\\emph{Panel A. FPC on vs.\\ off (Design B)}} \\\\",
  "\\addlinespace[2pt]",
  "Rung & Estimator & SE/SD & Coverage \\\\",
  "\\midrule")

for (ru in rungs) {
  first_ru <- TRUE
  for (ar in arms) {
    no_ratio  <- r3(getA(ru, ar, "no",  "se_ratio"));  no_cov  <- f3(getA(ru, ar, "no",  "coverage"))
    yes_ratio <- r3(getA(ru, ar, "yes", "se_ratio")); yes_cov <- f3(getA(ru, ar, "yes", "coverage"))
    ruhead <- if (first_ru) rung_lab[[ru]] else ""
    out <- c(out,
      sprintf("%s & %s (no FPC) & %s & %s \\\\", ruhead, arm_lab[[ar]], no_ratio,  no_cov),
      sprintf("%s & %s (FPC) & %s & %s \\\\",    "",     arm_lab[[ar]], yes_ratio, yes_cov))
    first_ru <- FALSE
  }
  if (ru != rungs[length(rungs)]) out <- c(out, "\\addlinespace")
}

out <- c(out,
  "\\midrule",
  "\\multicolumn{4}{@{}l}{\\emph{Panel B. First-stage fraction $f=m/M_{\\mathrm{pop}}$ (Fully-Aware-CF, L1)}} \\\\",
  "\\addlinespace[2pt]",
  "$J$ & $f$ & SE/SD & Coverage \\\\",
  "\\midrule")

for (Jv in c(64, 32, 16, 8)) {
  out <- c(out, sprintf("%d & %s & %s & %s \\\\",
                        Jv, f3(getB(Jv, "frac")),
                        r3(getB(Jv, "se_ratio")), f3(getB(Jv, "coverage"))))
}

out <- c(out, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(out, "outputs/tables/webF_fpc.tex")
cat(paste(out, collapse = "\n"), "\n")
