# Render the number-of-folds (V) sensitivity of the cross-fitted estimator as
# a LaTeX table fragment for Web Appendix F. Design-A population, V in
# {2, 5, 10} at the smooth (L2) and aggressive (L4) rungs; V = 5 is the
# headline configuration, so those rows double as an internal consistency
# anchor for the main results. Only the Fully-Aware-CF arm varies with V.
# Numbers straight from: results/J5_vfolds_summary.csv
# Output: outputs/tables/webF_vfolds.tex   (label tab:webF_vfolds)

a <- read.csv("results/J5_vfolds_summary.csv", stringsAsFactors = FALSE)

f3 <- function(x) sprintf("%.3f", x + sign(x) * 5e-7)

rungs    <- c("L2_smooth", "L4_aggressive")
rung_lab <- c(L2_smooth = "L2 (smooth)", L4_aggressive = "L4 (aggressive)")
Vs       <- c(2L, 5L, 10L)

G <- function(rung, V, col) {
  v <- a[[col]][a$rung == rung & a$V_cf == V & a$method == "Fully-Aware-CF"]
  if (length(v) == 1) v else stop(sprintf("J5: no CF row for %s/V=%d", rung, V))
}

rows <- character(0)
for (rg in rungs) {
  for (V in Vs) {
    lab <- if (V == Vs[1]) rung_lab[[rg]] else ""
    vtxt <- if (V == 5L) "\\textbf{5 (headline)}" else as.character(V)
    rows <- c(rows, paste0(
      lab, " & ", vtxt,
      " & ", f3(G(rg, V, "bias")), " & ", f3(G(rg, V, "se_ratio")),
      " & ", f3(G(rg, V, "coverage")), " & ", f3(G(rg, V, "mcse_cov")), " \\\\"))
  }
  if (rg != rungs[length(rungs)]) rows <- c(rows, "\\addlinespace")
}

out <- c(
  "% Auto-generated by simulation/renderers/render_vfolds_tex.R -- do not edit by hand.",
  "% Source: results/J5_vfolds_summary.csv.",
  "\\begin{table}[H]\\centering\\small",
  paste0("\\caption{Number-of-folds sensitivity of the primary cross-fitted ",
         "estimator (Fully-Aware-CF; Design~A, $1000$ replicates per cell). ",
         "PSU-level folds $V\\in\\{2,5,10\\}$, balanced within strata, at the ",
         "smooth (L2) and aggressive (L4) rungs; $V=5$ is the headline ",
         "configuration used throughout the paper. Bias, SE/SD, and coverage ",
         "are stable in $V$ at both rungs (all coverage differences within ",
         "twice the Monte Carlo standard error), so the fold count is not a ",
         "hidden tuning parameter of the reported results; the other four ",
         "arms do not use the folds and are $V$-invariant by construction.}"),
  "\\label{tab:webF_vfolds}",
  "\\begin{tabular}{@{}ll cccc@{}}",
  "\\toprule",
  "Rung & $V$ & Bias & SE/SD & Coverage & MC se \\\\",
  "\\midrule",
  rows,
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{table}")

writeLines(out, "outputs/tables/webF_vfolds.tex")
cat("wrote outputs/tables/webF_vfolds.tex\n")
