# Render the per-rung product nuisance rate (R04_nuisance_rate) as a compact
# LaTeX table for Web Appendix D. One row per ladder rung, columns for each of
# the two designs: the realized sqrt(m)-scaled outcome/propensity product error
# and its ratio to the L1 parametric baseline (prod_sqrtm_vs_L1). The ratio is
# the quantity quoted in prose: ~1 at L1-L3 (consistent with the root-m product
# rate Theorem 1 assumes), blowing up at L4 (the deliberate interpolating-RF
# strawman that violates any product rate by construction).
# Numbers straight from results/R04_nuisance_rate_summary.csv.
# Output: outputs/tables/webD_rate.tex
d <- read.csv("results/R04_nuisance_rate_summary.csv", stringsAsFactors = FALSE)

# Design A = 'standard' (n=1,518); Design B = 'R1' (n=2,034, NHANES-like, R1 regime)
rungs    <- c("L1_param", "L2_smooth", "L3_adaptive", "L4_aggressive")
rung_lab <- c(L1_param = "L1 (param)", L2_smooth = "L2 (smooth)",
              L3_adaptive = "L3 (adaptive)", L4_aggressive = "L4 (aggressive)")

f2 <- function(x) sprintf("%.2f", x + sign(x) * 5e-9)   # 2 dp, round half away from 0

cell <- function(scen, rung, col) {
  v <- d[[col]][d$scenario == scen & d$rung == rung]
  if (length(v) == 1) f2(v) else ""
}

out <- c(
  "% Auto-generated by codes/render_rate_tex.R -- do not edit by hand.",
  "% Source: results/R04_nuisance_rate_summary.csv (R04_nuisance_rate).",
  "\\begin{table}[H]\\centering\\small",
  paste0("\\caption{Realized product nuisance rate across the Super Learner ",
         "complexity ladder, both designs. For each rung we report the ",
         "$\\sqrt{m}$-scaled product of the out-of-fold outcome and propensity ",
         "root-mean-squared errors against the known $(Q_0,g_0)$ ",
         "($\\sqrt{m}\\,\\widehat e_Q\\,\\widehat e_g$), and its ratio to the ",
         "well-specified parametric baseline L1 (`vs L1'). A ratio near $1$ is ",
         "consistent with the root-$m$ product rate that Theorem~1 assumes ",
         "(Web Appendix~A, Assumption on the product rate); it holds through the ",
         "realistic adaptive ensemble L3 and blows up only at the deliberate ",
         "interpolating-forest stress test L4, which violates any product rate by ",
         "construction. Design A is `standard' ($n=1{,}518$); Design B is the ",
         "NHANES-like R1 regime ($n=2{,}034$). $200$ replicates per cell.}"),
  "\\label{tab:webD_rate}",
  "\\begin{tabular}{@{}l cc cc@{}}",
  "\\toprule",
  "& \\multicolumn{2}{c}{Design A} & \\multicolumn{2}{c}{Design B (NHANES-like)} \\\\",
  "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
  "Rung & $\\sqrt{m}\\,\\widehat e_Q\\widehat e_g$ & vs L1 & $\\sqrt{m}\\,\\widehat e_Q\\widehat e_g$ & vs L1 \\\\",
  "\\midrule")

for (r in rungs) {
  rl <- rung_lab[[r]]
  pA <- cell("standard", r, "mean_prod_sqrtm"); rA <- cell("standard", r, "prod_sqrtm_vs_L1")
  pB <- cell("R1",       r, "mean_prod_sqrtm"); rB <- cell("R1",       r, "prod_sqrtm_vs_L1")
  if (r == "L4_aggressive") {
    rl <- sprintf("\\textbf{%s}", rl)
    rA <- sprintf("\\textbf{%s}", rA); rB <- sprintf("\\textbf{%s}", rB)
  }
  out <- c(out, sprintf("%s & %s & %s & %s & %s \\\\", rl, pA, rA, pB, rB))
}

out <- c(out, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(out, "outputs/tables/webD_rate.tex")
cat(paste(out, collapse = "\n"), "\n")
