# =====================================================================
# render_webD_control_tex.R  --  Web Appendix D pipeline-correctness control
# table, generated from the R01_simple_control aggregated summary
# (no hand transcription). Matched correctly-specified ('simple') versus
# Kang-Schafer-misspecified ('complex') parametric rung L1, plus the
# correctly-specified smooth rung L2, for both designs and all five arms.
# Output: outputs/tables/webD_control.tex
# Source: results/R01_simple_control_summary.csv (1000-rep ARC run).
# =====================================================================
d <- read.csv("results/R01_simple_control_summary.csv", check.names = FALSE)

scen_lab <- c(standard = "Design A", R1 = "Design B")
scen_ord <- c("standard", "R1")
mt_lab   <- c(simple = "Correctly specified (\\texttt{simple})",
              complex = "Misspecified, Kang--Schafer (\\texttt{complex})")
mt_ord   <- c("simple", "complex")
rung_lab <- c(L1_param = "L1 (GLM)", L2_smooth = "L2 (+GAM, MARS)")
rung_ord <- c("L1_param", "L2_smooth")
meth_ord <- c("Fully-Aware", "Fully-Aware-CF", "Fully-Aware-CV",
              "Partially-Aware", "Non-Aware")
meth_lab <- c("Fully-Aware (single-fit)", "Fully-Aware-CF", "Fully-Aware-CV",
              "Partially-Aware", "Non-Aware")
names(meth_lab) <- meth_ord

bsign <- function(x) sprintf("%+.3f", x)
f3 <- function(x) sprintf("%.3f", x)
f2 <- function(x) sprintf("%.2f", x)

out <- c(
  "% Auto-generated by codes/render_webD_control_tex.R -- do not edit by hand.",
  "% Source: results/R01_simple_control_summary.csv (R01_simple_control, 1000-rep ARC run).",
  "\\begin{table}[H]\\centering\\small",
  paste0("\\caption{Pipeline-correctness control (R01): matched correctly-specified ",
         "(\\texttt{simple}, identity covariate transform) versus Kang--Schafer-misspecified ",
         "(\\texttt{complex}, the headline population) nuisance specification, over 1{,}000 ",
         "replicates, for both designs and all five arms. Reported are bias, empirical standard ",
         "deviation (SD), mean estimated standard error (SE), the SE-to-SD ratio, and Wald ",
         "coverage of nominal 0.95 intervals. Under correct specification the lower-rung bias ",
         "collapses toward zero and coverage returns to nominal, whereas under the ",
         "Kang--Schafer misspecification a small positive bias and slightly degraded coverage ",
         "appear at L1; the cross-fitting and design-based-variance machinery is identical ",
         "across the two blocks. The unweighted Non-Aware arm under-covers under both ",
         "specifications. Monte Carlo standard error of coverage is about 0.01.}"),
  "\\label{tab:webD_control}",
  "\\begin{tabular}{@{}ll rrrr r@{}}", "\\toprule",
  "Design & Estimator & Bias & SD & SE & SE:SD & Coverage \\\\", "\\midrule")

for (mt in mt_ord) {
  out <- c(out, sprintf("\\multicolumn{7}{@{}l}{\\textit{%s}}\\\\", mt_lab[[mt]]))
  for (r in rung_ord) {
    sub_r <- d[d$model_type == mt & d$rung == r, ]
    if (nrow(sub_r) == 0) next
    out <- c(out, sprintf("\\multicolumn{7}{@{}l}{\\quad\\textit{%s}}\\\\", rung_lab[[r]]))
    for (scn in scen_ord) {
      first <- TRUE
      for (m in meth_ord) {
        row <- sub_r[sub_r$scenario == scn & sub_r$method == m, ]
        if (nrow(row) == 0) next
        dlab <- if (first) scen_lab[[scn]] else ""
        out <- c(out, sprintf("%s & \\quad %s & %s & %s & %s & %s & %s \\\\",
                              dlab, meth_lab[[m]], bsign(row$bias), f3(row$emp_sd),
                              f3(row$mean_se), f2(row$se_ratio), f3(row$coverage)))
        first <- FALSE
      }
    }
    out <- c(out, "\\addlinespace")
  }
}

out <- c(out, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(out, "outputs/tables/webD_control.tex")
cat(paste(out, collapse = "\n"), "\n")
cat("\n\n--- wrote outputs/tables/webD_control.tex ---\n")
