# =====================================================================
# render_helpers_color.R  —  ONE shared source of truth for appendix-table
# colour + number formatting, so every Web-Appendix table (new and existing)
# is styled identically. source() this at the top of every render_*.R that
# emits an appendix table. Palette = Okabe-Ito, matching the CSEB talk so the
# slides and the paper agree. Requires colortbl + the \definecolor block in
# the appendix preamble (cfBlue/warnRed/headGrey/cfTint/warnTint).
#
# Semantics carried by colour (consistent across tables):
#   * header row            -> \rowcolor{headGrey}     (readability)
#   * the primary CF row   -> \rowcolor{cfTint}        (eye finds the recommended estimator)
#   * coverage cell < 0.90   -> \cellcolor{warnTint}     (single-fit / CV collapse "lights up")
#   * type-I cell > 0.075    -> \cellcolor{warnTint}     (design-naive over-rejection lights up)
# Main-text tables/figures stay B&W (Biometrics print); this is appendix-only.
# =====================================================================

# ---- number formatting (matches the existing render_webD_tex.R) ----
.bsign <- function(x) sprintf("%+.3f", x)
.f3    <- function(x) sprintf("%.3f", x)
.f2    <- function(x) sprintf("%.2f", x)

# ---- header row: wrap the column-header line so it gets the header shade ----
hdr_row <- function(header_line) paste0("\\rowcolor{headGrey} ", header_line)

# ---- primary cross-fitted row tint: returns the \rowcolor token (or "") ----
# `method` = the row's estimator label; `primary` = the exact label to tint
# (e.g. "Fully-Aware-CF", "Fully-Aware-CF-h", "AIPW-CF", "CF-u").
cf_row <- function(method, primary) if (identical(as.character(method), primary)) "\\rowcolor{cfTint} " else ""

# ---- coverage cell: shade if anti-conservative (< thresh); format to 3 dp ----
cov_cell <- function(x, thresh = 0.90) {
  if (length(x) != 1 || is.na(x)) return("---")
  v <- .f3(x)
  if (x < thresh) paste0("\\cellcolor{warnTint}", v) else v
}

# ---- type-I cell: shade if inflated (> hi) relative to the 0.05 target ----
typeI_cell <- function(x, hi = 0.075) {
  if (length(x) != 1 || is.na(x)) return("---")
  v <- .f3(x)
  if (x > hi) paste0("\\cellcolor{warnTint}", v) else v
}

# ---- standard auto-gen banner for the .tex header ----
gen_banner <- function(script, src)
  c(sprintf("%% Auto-generated by %s -- do not edit by hand.", script),
    sprintf("%% Source: %s", src),
    "%% Colour via simulation/renderers/render_helpers_color.R (palette defined in appendix preamble).")
