# Render the known-truth limited-overlap (positivity-stress) simulation as a
# LaTeX table fragment for Web Appendix F. The stress knob is the confounding
# strength alpha_g in the treatment model (odds ratio exp(alpha_g) per unit of
# the confounder sum); the treatment intercept is re-solved to hold the
# marginal P(A=1) fixed, so increasing alpha_g stretches the true propensity
# toward {0,1} WITHOUT changing the outcome law -- the super-population truth
# Psi is invariant by construction (verified in the source CSV).
# Numbers straight from: results/J4_overlap_summary.csv
# Output: outputs/tables/webF_overlapsim.tex  (label tab:webF_overlapsim)

a <- read.csv("results/J4_overlap_summary.csv", stringsAsFactors = FALSE)

f3 <- function(x) sprintf("%.3f", x + sign(x) * 5e-7)
f1 <- function(x) sprintf("%.1f", x)

cells <- rbind(
  data.frame(rung = "L2_smooth",     atag = c("base", "mid", "high")),
  data.frame(rung = "L4_aggressive", atag = c("base", "high")))
rung_lab <- c(L2_smooth = "L2", L4_aggressive = "L4")

G <- function(rung, atag, arm, col) {
  v <- a[[col]][a$rung == rung & a$alpha_tag == atag & a$method == arm]
  if (length(v) == 1) v else stop(sprintf("J4: no row for %s/%s/%s", rung, atag, arm))
}

# Psi invariance guard (the table's design premise; hard-stop if violated)
psis <- unique(round(a$Psi, 6))
stopifnot(length(psis) == 1)

rows <- character(0)
for (i in seq_len(nrow(cells))) {
  rg <- cells$rung[i]; at <- cells$atag[i]
  orv <- f1(exp(G(rg, at, "Fully-Aware", "alpha_g")))
  rows <- c(rows, paste0(
    rung_lab[[rg]], " & ", orv,
    " & ", f3(G(rg, at, "Fully-Aware", "bias")),
    " & ", f3(G(rg, at, "Fully-Aware", "se_ratio")),
    " & ", f3(G(rg, at, "Fully-Aware", "coverage")),
    " & ", f3(G(rg, at, "Fully-Aware-CF", "bias")),
    " & ", f3(G(rg, at, "Fully-Aware-CF", "se_ratio")),
    " & ", f3(G(rg, at, "Fully-Aware-CF", "coverage")), " \\\\"))
}

out <- c(
  "% Auto-generated by simulation/renderers/render_overlapsim_tex.R -- do not edit by hand.",
  "% Source: results/J4_overlap_summary.csv.",
  "\\begin{table}[H]\\centering\\small",
  paste0("\\caption{Known-truth limited-overlap stress test (Design~A, $1000$ ",
         "replicates per cell; two cells retain $999$ after a per-replicate ",
         "fit-failure guard). The confounding odds ratio $e^{\\alpha_g}$ per ",
         "unit of the confounder sum is raised from the headline $1.3$ to ",
         "$2.5$ and $5.0$ with the marginal treatment prevalence held fixed, ",
         "stretching the true propensity toward $\\{0,1\\}$ while leaving the ",
         "super-population truth $\\Psi$ unchanged. Columns give bias, SE/SD, ",
         "and $95\\%$ coverage for the single-fit Fully-Aware and the primary ",
         "cross-fitted Fully-Aware-CF arms. At the headline overlap the ",
         "cross-fit is calibrated where the single fit collapses (L4). Under ",
         "genuine near-positivity violation both arms degrade: the imposed ",
         "$0.05$ propensity floor then acts as real truncation, and the bias ",
         "it induces is not a variance failure --- these cells sit outside the ",
         "positivity envelope of the theory (Assumptions on treatment ",
         "positivity and bounded relative weights, Web Appendix~A). ",
         "Cross-fitting dominates the single fit at every overlap level but ",
         "is not a remedy for absent overlap.}"),
  "\\label{tab:webF_overlapsim}",
  "\\begin{tabular}{@{}lc ccc ccc@{}}",
  "\\toprule",
  " & & \\multicolumn{3}{c}{Fully-Aware (single fit)} & \\multicolumn{3}{c}{\\textbf{Fully-Aware-CF}} \\\\",
  "\\cmidrule(lr){3-5}\\cmidrule(lr){6-8}",
  "Rung & $e^{\\alpha_g}$ & Bias & SE/SD & Coverage & Bias & SE/SD & Coverage \\\\",
  "\\midrule",
  rows,
  "\\bottomrule",
  "\\end{tabular}",
  "\\end{table}")

writeLines(out, "outputs/tables/webF_overlapsim.tex")
cat("wrote outputs/tables/webF_overlapsim.tex\n")
