# Render the in-sample propensity-overlap table (single-fit Fully-Aware vs
# cross-fitted Fully-Aware-CF) for Web Appendix F, from the NHANES deep-learner
# ladder diagnostics. All four examples x rungs L1-L4. Numbers straight from
# nhanes_diagnostics.csv.
# Output: outputs/tables/webF_overlap.tex
d <- read.csv("results/nhanes_diagnostics.csv",
              stringsAsFactors = FALSE)

exs    <- c("E1", "E2", "E3", "E4")
ex_lab <- c(E1 = "E1 (sleep)", E2 = "E2 (food)", E3 = "E3 (e-cig)", E4 = "E4 (GDM)")
rungs  <- c("L1_param", "L2_smooth", "L3_adaptive", "L4_aggressive")
rung_lab <- c(L1_param = "L1", L2_smooth = "L2",
              L3_adaptive = "L3", L4_aggressive = "L4")

f3  <- function(x) sprintf("%.3f", x)
rng <- function(lo, hi) sprintf("[%s, %s]", f3(lo), f3(hi))
pct <- function(x) sprintf("%.0f\\%%", 100 * x)

out <- c(
  "% Auto-generated by nhanes/render_overlap_tex.R -- do not edit by hand.",
  "% Source: results/nhanes_diagnostics.csv",
  "\\begin{table}[H]\\centering\\small",
  paste0("\\caption{In-sample propensity overlap by Super Learner ladder rung ",
         "for the single-fit (Fully-Aware) versus cross-fitted (Fully-Aware-CF) ",
         "nuisances, for the four NHANES illustrations. ",
         "`\\% near bound' is the share of units with estimated propensity within ",
         "$0.05$ of $0$ or $1$. Only at the deepest rung (L4) does the single-fit ",
         "propensity reach exactly $0$ and $1$ (in-sample separation); the ",
         "out-of-fold cross-fit propensity stays bounded, with an imposed lower ",
         "floor of $0.05$ and a data-driven upper range.}"),
  "\\label{tab:nhoverlap}",
  "\\begin{tabular}{@{}ll ccc@{}}",
  "\\toprule",
  "Example & Rung & Single-fit $g$ range & Single-fit \\% near bound & Cross-fit $g$ range \\\\",
  "\\midrule")

for (ex in exs) {
  rows  <- d[d$example == ex, ]
  first <- TRUE
  for (r in rungs) {
    rr <- rows[rows$rung == r, ]
    if (nrow(rr) == 0) next
    exhead <- if (first) ex_lab[[ex]] else ""
    rl     <- rung_lab[[r]]
    fa_rng <- rng(rr$g_fa_min, rr$g_fa_max)
    if (r == "L4_aggressive") { rl <- sprintf("\\textbf{%s}", rl)
                                fa_rng <- sprintf("\\textbf{%s}", fa_rng) }
    out <- c(out, sprintf("%s & %s & %s & %s & %s \\\\",
                          exhead, rl, fa_rng, pct(rr$g_fa_near_bound),
                          rng(rr$g_cf_min, rr$g_cf_max)))
    first <- FALSE
  }
  if (ex != exs[length(exs)]) out <- c(out, "\\addlinespace")
}

out <- c(out, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(out, "outputs/tables/webF_overlap.tex")
cat(paste(out, collapse = "\n"), "\n")
