# Render the real-data isolation table (propensity floor and de-weighting are not
# the rescue) for Web Appendix F, from the R05_harmonized_floor run. Rows are
# (example x rung) for the two poorest-overlap NHANES examples E3 and E4 across
# the L1-L4 ladder; columns give the four arm point estimates --
#   b_FA      Fully-Aware       (single-fit, weighted, default propensity bound)
#   b_FA_h05  Fully-Aware-h05   (single-fit at the harmonized 0.05 floor)
#   b_CF      Fully-Aware-CF    (primary cross-fit, UNWEIGHTED OOF nuisances)
#   b_CF_wOOF Fully-Aware-CF-wOOF (cross-fit, WEIGHTED OOF nuisances comparator)
# -- plus the headline single-fit-vs-cross-fit divergence d_FA_CF. The
# weighted-OOF arm is NA (non-converged divergence guard) at L1 for both E3 and
# E4; those cells print as a dash. Numbers straight from
# results/R05_point_divergence.csv.
# Output: outputs/tables/webF_isofloor.tex
d <- read.csv("results/R05_point_divergence.csv", stringsAsFactors = FALSE)

exs    <- c("E3", "E4")
ex_lab <- c(E3 = "E3 (e-cig)", E4 = "E4 (GDM)")
rungs  <- c("L1_param", "L2_smooth", "L3_adaptive", "L4_aggressive")
rung_lab <- c(L1_param = "L1", L2_smooth = "L2",
              L3_adaptive = "L3", L4_aggressive = "L4")

# round half away from zero, then format; NA -> em-dash
f3 <- function(x) ifelse(is.na(x), "---", sprintf("%.3f", x + sign(x) * 5e-7))
get <- function(ex, rung, col) {
  r <- d[d$example == ex & d$rung == rung, ]
  if (nrow(r) != 1) stop(sprintf("R05: expected 1 row for %s %s", ex, rung))
  r[[col]]
}

out <- c(
  "% Auto-generated by codes/render_isofloor_tex.R -- do not edit by hand.",
  "% Source: results/R05_point_divergence.csv (R05 harmonized-floor isolation).",
  "\\begin{table}[H]\\centering\\small",
  paste0("\\caption{Real-data isolation of the propensity floor and de-weighting ",
         "for the two poorest-overlap NHANES illustrations (E3 e-cigarette use, ",
         "E4 gestational diabetes), across the L1--L4 complexity ladder. Columns ",
         "give four arm point estimates: single-fit at the default bound ",
         "(Fully-Aware), single-fit at the harmonized $0.05$ propensity floor ",
         "(Fully-Aware-h05), the primary cross-fitted arm with unweighted ",
         "out-of-fold (OOF) nuisances (Fully-Aware-CF), and the comparator ",
         "cross-fitted arm with weighted OOF nuisances (Fully-Aware-CF-wOOF); the ",
         "final column is the single-fit-vs-cross-fit divergence ",
         "$d_{\\mathrm{FA,CF}}=|\\text{FA}-\\text{CF}|$. Fully-Aware equals ",
         "Fully-Aware-h05 to all printed digits in every cell, so the floor does ",
         "not drive the divergence; where it converges the weighted-OOF arm lands ",
         "on the cross-fit side; and the weighted-OOF arm fails to converge ",
         "(`---') at L1 for both examples. Conclusions are anchored on L3.}"),
  "\\label{tab:webF_isofloor}",
  "\\begin{tabular}{@{}ll cccc c@{}}",
  "\\toprule",
  "Example & Rung & FA & FA-h05 & CF & CF-wOOF & $d_{\\mathrm{FA,CF}}$ \\\\",
  "\\midrule")

for (ex in exs) {
  first <- TRUE
  for (r in rungs) {
    exhead <- if (first) ex_lab[[ex]] else ""
    out <- c(out, sprintf("%s & %s & %s & %s & %s & %s & %s \\\\",
                          exhead, rung_lab[[r]],
                          f3(get(ex, r, "b_FA")),   f3(get(ex, r, "b_FA_h05")),
                          f3(get(ex, r, "b_CF")),   f3(get(ex, r, "b_CF_wOOF")),
                          f3(get(ex, r, "d_FA_CF"))))
    first <- FALSE
  }
  if (ex != exs[length(exs)]) out <- c(out, "\\addlinespace")
}

out <- c(out, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(out, "outputs/tables/webF_isofloor.tex")
cat(paste(out, collapse = "\n"), "\n")
