# =====================================================================
# nhanes/render_table2_tex.R
# Builds the main-text Table 2 as the FIVE-ARM decomposition (was two-arm).
# Risk differences are the m=40 multiple-imputation (Rubin) estimates for ALL
# five arms, from results/R06_mi_summary.csv (run R06_mi). The n / exposed
# header and the min-ghat (single / CF) footer are the primary-preview context
# columns carried verbatim from the prior table (unchanged by imputation count).
# Writes outputs/tables/table2_nhanes.tex.
# =====================================================================
mi  <- read.csv("results/R06_mi_summary.csv", stringsAsFactors = FALSE)
EX  <- c("E1", "E2", "E3", "E4")
ARMS <- c("Non-Aware", "Partially-Aware", "Fully-Aware", "Fully-Aware-CV", "Fully-Aware-CF")
ARMLAB <- c("Non-Aware", "Partially-Aware", "Fully-Aware", "Fully-Aware-CV",
            "\\textbf{Fully-Aware-CF}")

# format a signed number with the project's tex minus convention ($-$).
# round() first (matching the audit's eqd, which uses round(.,3)) so boundary
# values like 0.10349999 -> 0.104, not the sprintf truncation 0.103.
sgn <- function(x) sub("^-", "$-$", sprintf("%.3f", round(x, 3)))
cell <- function(b, lcl, ucl) sprintf("%s (%s, %s)", sgn(b), sgn(lcl), sgn(ucl))

get <- function(ex, arm) {
  r <- mi[mi$example == ex & mi$method == arm, ]
  if (!nrow(r)) stop("missing MI row: ", ex, " / ", arm)
  cell(r$b[1], r$lcl[1], r$ucl[1])
}

# fixed context (primary-preview diagnostics; carried verbatim, audited)
nlab   <- c(E1 = "30{,}983 (37\\%)", E2 = "29{,}359 (20\\%)",
            E3 = "10{,}736 (18\\%)", E4 = "10{,}956 (6\\%)")
minghat <- c(E1 = "0.13 / 0.13", E2 = "0.004 / 0.05",
             E3 = "0.002 / 0.05", E4 = "0.001 / 0.05")

L <- c(
  "% Auto-generated by nhanes/render_table2_tex.R -- do not edit by hand.",
  "% Five-arm decomposition; RDs are m=40 multiple imputation (Rubin) from",
  "% results/R06_mi_summary.csv. n/exposed and min-ghat are the primary-",
  "% preview context columns (unchanged by the imputation count).",
  "\\begin{tabular}{@{}l cccc@{}}",
  "\\toprule",
  "Estimator & E1 & E2 & E3 & E4 \\\\",
  "& sleep $\\to$ obesity & food insec.\\ $\\to$ depr. & e-cig $\\to$ HTN & GDM $\\to$ HTN \\\\",
  sprintf("$n$ (exposed) & %s & %s & %s & %s \\\\", nlab["E1"], nlab["E2"], nlab["E3"], nlab["E4"]),
  "\\midrule",
  "\\multicolumn{5}{@{}l}{\\emph{Risk difference (95\\% CI), multiple imputation $m{=}40$}}\\\\")

for (k in seq_along(ARMS)) {
  L <- c(L, sprintf("%s & %s & %s & %s & %s \\\\", ARMLAB[k],
                    get("E1", ARMS[k]), get("E2", ARMS[k]),
                    get("E3", ARMS[k]), get("E4", ARMS[k])))
}

L <- c(L,
  "\\midrule",
  sprintf("min $\\hat g$ (single / CF) & %s & %s & %s & %s \\\\",
          minghat["E1"], minghat["E2"], minghat["E3"], minghat["E4"]),
  "\\bottomrule",
  "\\end{tabular}")

writeLines(L, "outputs/tables/table2_nhanes.tex")
cat("wrote outputs/tables/table2_nhanes.tex (five-arm MI)\n")
cat(paste(L, collapse = "\n"), "\n")
