# =====================================================================
# render_webD_tex.R  —  Web Appendix D tables, generated from
# results/sim_full_summary.csv + sim_full_diagnostics.csv (no hand transcription).
# Output: Writing/Appendix/webD_results.tex
#   - one compact results table per design (short rung headers -> fit page width)
#   - one design-diagnostics table (DEFF/ICC/V_eff/g-ranges), so the results
#     tables stay narrow (previous wide rung-header lines overflowed on A4).
# =====================================================================
s <- read.csv("results/sim_full_summary.csv", check.names = FALSE)
g <- read.csv("results/sim_full_diagnostics.csv", check.names = FALSE)

rung_lab <- c(L1_param = "L1 (GLM)", L2_smooth = "L2 (+GAM, MARS)",
              L3_adaptive = "L3 (+RF)", L4_aggressive = "L4 (deep RF)")
rung_ord <- names(rung_lab)
meth_ord <- c("Fully-Aware", "Fully-Aware-CF", "Fully-Aware-CV",
              "Partially-Aware", "Non-Aware")
meth_lab <- c("Fully-Aware (single-fit)", "Fully-Aware-CF", "Fully-Aware-CV",
              "Partially-Aware", "Non-Aware")
names(meth_lab) <- meth_ord
scen_lab <- c(standard = "Design A ($H=10$ strata, $\\approx 6$ PSUs/stratum, $n=1{,}518$)",
              R1 = "Design B ($H=50$ strata, 2 PSUs/stratum, NHANES-like, $n=2{,}034$)")

bsign <- function(x) sprintf("%+.3f", x)
f3 <- function(x) sprintf("%.3f", x)
f2 <- function(x) sprintf("%.2f", x)

emit_results <- function(scn) {
  out <- c("\\begin{table}[H]\\centering\\small")
  out <- c(out, sprintf("\\caption{Full simulation results --- %s. Over 1{,}000 replicates: bias, empirical standard deviation (SD), mean estimated standard error (SE), the SE-to-SD ratio, and Wald coverage of nominal 0.95 intervals (referred to a $t$ distribution with the survey degrees of freedom). Fully-Aware-CV is defined only at the multi-learner rungs L2--L3. Per-rung design diagnostics are in Web Table~\\ref{tab:webD_diag}; Monte Carlo standard error of coverage is about 0.01.}", scen_lab[[scn]]))
  out <- c(out, sprintf("\\label{tab:webD_%s}", scn))
  out <- c(out, "\\begin{tabular}{@{}l rrrr r@{}}", "\\toprule",
           "Estimator & Bias & SD & SE & SE:SD & Coverage \\\\", "\\midrule")
  for (r in rung_ord) {
    out <- c(out, sprintf("\\multicolumn{6}{@{}l}{\\textit{%s}}\\\\", rung_lab[[r]]))
    sub <- s[s$scenario == scn & s$rung == r, ]
    for (m in meth_ord) {
      row <- sub[sub$method == m, ]
      if (nrow(row) == 0) next
      out <- c(out, sprintf("\\quad %s & %s & %s & %s & %s & %s \\\\",
                            meth_lab[[m]], bsign(row$bias), f3(row$emp_sd),
                            f3(row$mean_se), f2(row$se_ratio), f3(row$coverage)))
    }
    if (r != rung_ord[length(rung_ord)]) out <- c(out, "\\addlinespace")
  }
  c(out, "\\bottomrule", "\\end{tabular}", "\\end{table}")
}

emit_diag <- function() {
  out <- c("\\begin{table}[H]\\centering\\small")
  out <- c(out, "\\caption{Influence-function design diagnostics by rung and design (1{,}000 replicates): the clustering-only design effect (DEFF) and intracluster correlation (ICC) of the realized influence function, the effective number of cross-fitting folds, and the minimum-to-maximum estimated propensity for the single-fit and cross-fitted estimators. At L4 the single-fit propensity reaches the boundary while cross-fitting stays bounded.}")
  out <- c(out, "\\label{tab:webD_diag}")
  out <- c(out, "\\begin{tabular}{@{}ll cc c cc@{}}", "\\toprule",
           "Design & Library & DEFF & ICC & $V_{\\mathrm{eff}}$ & $\\widehat g$ single-fit & $\\widehat g$ cross-fitted \\\\",
           "\\midrule")
  for (scn in c("standard", "R1")) {
    dlab <- if (scn == "standard") "Design A" else "Design B"
    for (i in seq_along(rung_ord)) {
      r <- rung_ord[i]; gr <- g[g$scenario == scn & g$rung == r, ]
      out <- c(out, sprintf("%s & %s & %s & %s & %d & $[%s,\\,%s]$ & $[%s,\\,%s]$ \\\\",
                            if (i == 1) dlab else "", rung_lab[[r]], f2(gr$deff), f3(gr$icc_eif),
                            gr$cf_V_eff, f3(gr$g_fa_min), f3(gr$g_fa_max),
                            f3(gr$g_cf_min), f3(gr$g_cf_max)))
    }
    if (scn == "standard") out <- c(out, "\\addlinespace")
  }
  c(out, "\\bottomrule", "\\end{tabular}", "\\end{table}")
}

tex <- paste(c(
  "% Auto-generated by codes/render_webD_tex.R -- do not edit by hand.",
  "% Source: results/sim_full_summary.csv + results/sim_full_diagnostics.csv (1000-rep ARC run).",
  paste(emit_results("standard"), collapse = "\n"), "",
  paste(emit_results("R1"), collapse = "\n"), "",
  paste(emit_diag(), collapse = "\n")), collapse = "\n")
writeLines(tex, "Writing/Appendix/webD_results.tex")
cat(tex)
cat("\n\n--- wrote Writing/Appendix/webD_results.tex ---\n")
