# Render the large-m sweep (R02_largem_sweep) as a compact LaTeX table fragment
# for Web Appendix F. The table makes the central contrast visible at a glance:
# as the number of PSUs per stratum m grows (m in {6,12,20,30}; m_total = m x J),
# the SINGLE-FIT Fully-Aware coverage DEGRADES at the interpolating rungs while
# the certified cross-fitted Fully-Aware-CF stays conservatively valid and FLAT.
#
#   Layout: one block per rung (L1, L3, RF_shallow, L4); within each block one
#   row per m, giving single-fit Fully-Aware coverage, then cross-fitted
#   Fully-Aware-CF coverage and its SE-to-SD ratio. Coverage at 3 dp; SE/SD at
#   2 dp. Design A ('standard'), 1000 replicates per cell.
#
# Numbers straight from:
#   results/arc/R02_largem_sweep_summary.csv
# Output: Writing/Appendix/webD_largem.tex   (label tab:webF_largem)

s <- read.csv("results/arc/R02_largem_sweep_summary.csv", stringsAsFactors = FALSE)

f3 <- function(x) sprintf("%.3f", x + sign(x) * 5e-7)   # coverage at 3 dp
r2 <- function(x) sprintf("%.2f", x + sign(x) * 5e-7)   # SE/SD at 2 dp

get1 <- function(rung, m, method, col) {
  v <- s[[col]][s$scenario == "standard" & s$rung == rung &
                s$base_m == m & s$method == method]
  if (length(v) == 1) v else stop(sprintf("R02: no row for %s/m=%d/%s/%s", rung, m, method, col))
}

ms       <- c(6, 12, 20, 30)
rungs    <- c("L1_param", "L3_adaptive", "RF_shallow", "L4_aggressive")
rung_lab <- c(L1_param      = "L1 (parametric)",
              L3_adaptive   = "\\textbf{L3 (adaptive)}",
              RF_shallow    = "RF (shallow)",
              L4_aggressive = "L4 (interpolating)")

out <- c(
  "% Auto-generated by codes/render_largem_tex.R -- do not edit by hand.",
  "% Source: results/arc/R02_largem_sweep_summary.csv (Design A 'standard', 1000 reps/cell).",
  "\\begin{table}[H]\\centering\\small",
  paste0("\\caption{Large-sample behaviour of single-fit versus cross-fitted ",
         "inference under the standard design (Design~A), sweeping the number of ",
         "PSUs per stratum $m$ (total ultimate clusters ",
         "$m_{\\mathrm{total}}=m\\times J$; $1000$ replicates per cell). ",
         "`SF cov.' is the empirical $95\\%$ Wald coverage of the single-fit ",
         "Fully-Aware estimator; `CF cov.' and `CF SE/SD' are the coverage and ",
         "the mean design SE divided by the empirical sampling SD (calibration; ",
         "$1$ is ideal) of the certified cross-fitted Fully-Aware-CF estimator. ",
         "As $m$ grows the single-fit coverage \\emph{degrades} at the ",
         "interpolating rungs (RF, L4), while Fully-Aware-CF stays ",
         "conservatively valid and flat. At L1 the cross-fitted coverage drifts ",
         "below nominal even though its SE stays calibrated ",
         "($\\mathrm{SE/SD}\\approx 1$): this is the Kang--Schafer ",
         "misspecification bias of Web Appendix~D, not a variance defect. ",
         "Robustness is anchored on the adaptive rung L3; RF and L4 are ",
         "deliberate strawmen retained to exhibit the single-fit failure.}"),
  "\\label{tab:webF_largem}",
  "\\begin{tabular}{@{}ll ccc@{}}",
  "\\toprule",
  "Rung & $m$ ($m_{\\mathrm{total}}$) & SF cov. & CF cov. & CF SE/SD \\\\",
  "\\midrule")

for (ru in rungs) {
  first_ru <- TRUE
  for (m in ms) {
    mtot   <- get1(ru, m, "Fully-Aware-CF", "m_total")
    sf_cov <- f3(get1(ru, m, "Fully-Aware",    "coverage"))
    cf_cov <- f3(get1(ru, m, "Fully-Aware-CF", "coverage"))
    cf_rat <- r2(get1(ru, m, "Fully-Aware-CF", "se_ratio"))
    ruhead <- if (first_ru) rung_lab[[ru]] else ""
    out <- c(out, sprintf("%s & %d (%d) & %s & %s & %s \\\\",
                          ruhead, m, mtot, sf_cov, cf_cov, cf_rat))
    first_ru <- FALSE
  }
  if (ru != rungs[length(rungs)]) out <- c(out, "\\addlinespace")
}

out <- c(out, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(out, "Writing/Appendix/webD_largem.tex")
cat(paste(out, collapse = "\n"), "\n")
