# Render the multiple-imputation diagnostics table (Web Appendix F) from the R06
# m=40 MI run, alongside the matched single-imputation certified estimates, for
# the certified Fully-Aware-CF arm. Columns: example, % incomplete cases (the m
# rule of White et al. 2011), m, fraction of missing information (FMI), the MI
# risk difference (Rubin 95% CI), and the single-imputation risk difference.
# Output: Writing/Appendix/webF_mi.tex
# Sources: results/arc/R06_mi_summary.csv (MI, m=40) and
#          Nhanes/results/local_preview_summary.csv (single imputation).
mi <- read.csv("results/arc/R06_mi_summary.csv", stringsAsFactors = FALSE)
si <- read.csv("Nhanes/results/local_preview_summary.csv", check.names = FALSE,
               stringsAsFactors = FALSE)

exs    <- c("E1", "E2", "E3", "E4")
exlab  <- c(E1 = "E1 sleep $\\to$ obesity",
            E2 = "E2 food insec.\\ $\\to$ depression",
            E3 = "E3 e-cig $\\to$ hypertension",
            E4 = "E4 GDM $\\to$ hypertension")
# percentage of incomplete cases per analytic domain (from the analytic frames;
# = rows with >=1 missing covariate / domain n). These set the m rule.
pct_inc <- c(E1 = 18, E2 = 9, E3 = 13, E4 = 29)

g <- function(d, ex, col) { v <- d[[col]][d$example == ex & d$method == "Fully-Aware-CF"]; if (length(v)) v[1] else NA_real_ }
# round() to match R's rounding used by the number audit (eqd), so the table,
# main-text Table 2, and verify_inline_numbers.R all agree (e.g. E2 ucl 0.1035 -> 0.103).
r3 <- function(x) sprintf("%.3f", round(x, 3))
ci <- function(b, l, u) gsub("-", "$-$", paste0(r3(b), " (", r3(l), ", ", r3(u), ")"))

out <- c(
  "% Auto-generated by codes/render_mi_tex.R -- do not edit by hand.",
  "% Sources: results/arc/R06_mi_summary.csv (MI m=40); Nhanes/results/local_preview_summary.csv (single imp).",
  "\\begin{table}[H]\\centering\\small",
  paste0("\\caption{Multiple imputation of missing covariates for the certified ",
         "Fully-Aware-CF estimator. For each illustration: the percentage of ",
         "incomplete cases (which sets the number of imputations $m$ by the rule ",
         "of White, Royston and Wood, 2011), $m$, the estimated fraction of ",
         "missing information (FMI), the multiple-imputation risk difference ",
         "(Rubin's-rules $95\\%$ CI), and the matched single-imputation risk ",
         "difference. The conclusions are identical to single imputation in every ",
         "example; the FMI never exceeds $0.13$.}"),
  "\\label{tab:webF_mi}",
  "\\begin{tabular}{@{}l r r r l l@{}}",
  "\\toprule",
  "Illustration & \\% incompl. & $m$ & FMI & MI RD (95\\% CI) & Single-imp.\\ RD (95\\% CI) \\\\",
  "\\midrule")
for (ex in exs) {
  out <- c(out, sprintf("%s & %d\\%% & %d & %.3f & %s & %s \\\\",
    exlab[[ex]], pct_inc[[ex]], as.integer(g(mi, ex, "M")), g(mi, ex, "fmi"),
    ci(g(mi, ex, "b"), g(mi, ex, "lcl"), g(mi, ex, "ucl")),
    ci(g(si, ex, "b"), g(si, ex, "lcl"), g(si, ex, "ucl"))))
}
out <- c(out, "\\bottomrule", "\\end{tabular}", "\\end{table}")
writeLines(out, "Writing/Appendix/webF_mi.tex")
cat(paste(out, collapse = "\n"), "\n")
